# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MindFlashlight' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MindFlashlight

  target 'MindFlashlightTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MindFlashlightUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  pod 'Masonry'
  pod 'AFNetworking'
  pod 'MJRefresh'
  pod 'MBProgressHUD'
  pod 'YYModel'
  pod 'YYText'
#  pod 'BmobSDK'

end
