# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AroundTheDB' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AroundTheDB
    pod 'Masonry'
    pod 'AFNetworking'
    pod 'MJRefresh'
    pod 'MBProgressHUD'
    pod 'YYModel'
    pod 'SDWebImage'
    pod 'YYText'
    pod 'FMDB'
    pod 'BmobSDK'
    pod 'BaiduMapKit'
    pod 'BMKLocationKit'
    pod 'AVOSCloud'   # 数据存储、短信、社交、云引擎调用等基础服务模块
end
