# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SupermarketOperationAssistant' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SupermarketOperationAssistant
    pod 'Masonry'
    pod 'MJRefresh'
    pod 'MBProgressHUD'
    pod 'YYModel'
end
