# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'workshopManagement5s' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for workshopManagement5s
    pod 'IQKeyboardManager'
    pod 'AFNetworking'

end
