# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '超市运营助手' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 超市运营助手
    pod 'Masonry'
    pod 'MJRefresh'
    pod 'MBProgressHUD'
end
