# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PocketBasketballScore' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PocketBasketballScore
    pod 'Masonry'
    pod 'AFNetworking'
    pod 'MJRefresh'
    pod 'MBProgressHUD'
    pod 'YYModel'
    pod 'IQKeyboardManager'
    pod 'BmobSDK'
    pod 'JPush', '3.2.4-noidfa'
    pod 'JCore', '2.1.4-noidfa'
    pod 'JTCalendar'
end
