# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'quitSmokingRemind' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for quitSmokingRemind
    pod 'Masonry'
    pod 'AFNetworking'
    pod 'MJRefresh'
end
