# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoodLifeAndGoodHabits' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GoodLifeAndGoodHabits
    pod 'Masonry'
    pod 'MJRefresh'
    pod 'MBProgressHUD'
    pod 'YYModel'
    pod 'JCore', '2.1.4-noidfa'
    pod 'JPush', '3.2.4-noidfa'
    pod 'AVOSCloud'
end
