# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GameAlert' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GameAlert
    pod 'Masonry'
    pod 'AFNetworking'
    pod 'MJRefresh'
    pod 'MBProgressHUD'
    pod 'YYModel'
    pod 'IQKeyboardManager'
end
