# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PocketBooks' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PocketBooks
    pod 'Masonry'
    pod 'AFNetworking'
    pod 'MJRefresh'
    pod 'MBProgressHUD'
    pod 'YYModel'
    pod 'SDWebImage'
    pod 'YYText'
    pod 'FMDB'
    pod 'OpenSSL-Universal'
    pod 'IQKeyboardManager'
    pod 'BmobSDK'
end
