# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Simple Diary' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Simple Diary
    pod 'Masonry'
    pod 'AFNetworking'
    pod 'MJRefresh'
    pod 'MBProgressHUD'
    pod 'YYModel'
    pod 'SDWebImage'
    pod 'YYText'
    pod 'FMDB'
    pod 'OpenSSL-Universal'
    pod 'IQKeyboardManager'
    pod 'JCore', '2.1.4-noidfa'
    pod 'JPush', '3.2.4-noidfa'
    pod 'AVOSCloud'
end
