# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TransportationManagement' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TransportationManagement
    pod 'AFNetworking'
    pod 'Masonry'
    pod 'MJRefresh'
    pod 'MBProgressHUD'
    pod 'YYModel'
end
